### ISSUE TITLE
[ADD] Добавить возможность получения данных в MS Word

### ISSUE THREAD

**Issue by anry-das** [captim/Weather#7]
Добавить функционал получения информациив формате MS Word (*.docx) с помощью Apache POI.
Шаблон файла разработать заранее.
В шаблон включить наименование ресурса и основные параметры, полученные из источника.
При вызове этого функционала на основе шаблона формируется документ MS Word (путем замены макросов в шаблоне) и передается в ответе.
На стороне сервера полученный документ сохранять не нужно.

**Comment by captim** [comment]
Commit number: 0abecd6
