### ISSUE TITLE
[CONTROLLER] Исправления в контроллере

### ISSUE THREAD

**Issue by anry-das** [captim/Weather#8]
- в weatherApi.getRequest("sumy"); наверное нужно передавать переменную с именем города
- File template = new File("template.docx"); больше нигде не используется. Лучше эту переменную вынести в сервис
- в switch (api) необходимо добавить реакцию на неправильно введенный API

**Comment by captim** [comment]
Commit number: 78aeba7

**Comment by anry-das** [comment]
вот этот пункт

> File template = new File("template.docx"); больше нигде не используется. Лучше эту переменную вынести в сервис
не выполнен

**Comment by anry-das** [comment]
также лучше использовать
`this.getClass().getClassLoader().getResource("template.docx");`

**Comment by captim** [comment]
Commit number: d0e1b57
